baseurl = "https://danchia.github.io"
title = "Daniel's Musings"
theme = "m10c"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Daniel Chia"
  description = "Tech, Graphics, Robotics"
  keywords = "blog,developer,personal"

  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/danchia"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/DanielChiaJH"
